added an about section
Susmita-Dey/Moody-website pull request #62
Opened 2022-10-03 16:50 UTC by Vanshiii203

issue #34 
![Screenshot (449)](https://user-images.githubusercontent.com/94471189/193633680-03b74200-843b-4b58-91c6-a908d2ba3adf.png)

2022-10-04 15:28 UTC, imaaquibali requested changes
Please resolve the conflict!

2022-10-05 08:11 UTC, Vanshiii203 commented
> Please resolve the conflict!

@imaaquibali @Susmita-Dey resolved the conflicts

2022-10-05 15:34 UTC, imaaquibali approved these changes

2022-10-05 15:35 UTC, imaaquibali commented
@Vanshiii203 Nice work!

2022-10-05 15:35 UTC, merged